### ISSUE TITLE
custom email form

### ISSUE THREAD

**Issue by Shevonna** [Shevonna/VeganVictoria#7]
research customer email handler through firebase. if we can link the inquiries form to firebase then generate the email to go to the owner that would be great!

**Comment by basedvegan** [comment]
both locations will be using the same email:
veganbyvictorias@gmail.com

make drop down menu for users to select location they are messaging about

**Comment by Shevonna** [comment]
look to see if we can use automated emails through firebase. slacked out doc, not sure if it requires auth or not
